name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    if: false # job disabled. currently it is not possible to create public Maven repos: https://github.community/t/how-to-allow-unauthorised-read-access-to-github-packages-maven-repository/115517/8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # 0 indicates all history
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.0
      - name: Publish sshauthentication-api
        run: ./gradlew :sshauthentication-api:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
